version: '3'
services:
  logicus-ruby-app:
    build: ./Ruby
    ports:
      - "3000:3000"
    depends_on:
      - logicus-mongo-db 
      - db 

  db:
    image: postgres 
    environment:
      POSTGRES_PASSWORD: logicus 

  logicus-mongo-db:
    build: ./MongoDB 
    ports:
      - "27017:27017"

  logicus-icinga:
    build: ./Icinga 
    ports:
      - "80:80"
      - "443:443"
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node 
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.0
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    networks:
      - elk 
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    ports:
      - "5601:5601"
    networks:
      - elk 
    depends_on:
      - elasticsearch

  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "8090:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    networks:
      - elk 

  grafana: 
    image: grafana/grafana 
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=logicus 
    depends_on:
      - graphite 
    ports: 
      - "3080:3000"
    networks:
      - elk 

networks:
  default:
    external:
      name: logicus-network 
  
  logicus-network:
    driver: bridge

  elk:
    driver: bridge 

volumes:
  grafana_data:
    driver: local 
  esdata:
    driver: local
  postgres_data:
    driver: local 
  mysql_data:
    driver: local 
